version : '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:3.7.1
#    image: bitnami/zookeeper:3.4.14
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


